### ISSUE TITLE
CSS Module Error

### ISSUE THREAD

**Issue by mihirchronicles** [fullstackreact/react-yelp-clone#18]
Hello, new to React and can't seem to figure out the cause of an error.

```
NODE_ENV=development ./node_modules/.bin/hjs-dev-server
/PROJ/webpack.config.js:22
const cssModulesNames = '${isDev ? '[path][name]__[local]__' : ''}[hash:base64:5]';
                                                ^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mihirpatel/Desktop/life of mi/code/personal_projects/react-foodsearch/node_modules/hjs-webpack/bin/hjs-dev-server.js:17:12)
    at Module._compile (module.js:570:32)
Failed to load webpack config, please use like this
hjs-dev-server.js webpack.config.js
```

**Comment by Kevin-Do** [comment]
What was your solution to this error?
