### ISSUE TITLE
Can't `npm start` after addition of css modules to project

### ISSUE THREAD

**Issue by wajd** [fullstackreact/react-yelp-clone#26]
when attempting `npm start` after adding app.css in the Demo:css modules section of tutorial, this is returned:
TypeError: Cannot read property 'filter' of undefined
at findLoader (/Users/wjt/ReactProjects/welp/webpack.config.js:41:25)
at Object. (/Users/wjt/ReactProjects/welp/webpack.config.js:48:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object. (/Users/wjt/ReactProjects/welp/node_modules/hjs-webpack/bin/hjs-dev-server.js:17:12)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
Failed to load webpack config, please use like this
hjs-dev-server.js webpack.config.js 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! welp@1.0.0 start: `NODE_ENV=development ./node_modules/.bin/hjs-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the welp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wjt/.npm/_logs/2018-06-29T07_44_31_216Z-debug.log

current suggested solution in comments is deleting node_modules directory, replacing webpack config file w/ tutorial repo version and reinstalling dependencies, theorising that a change in technologies is the reason for the failure, but I would rather find out how to do this using the updated technologies.

**Comment by jimmyFlash** [comment]
I'm getting the same error because : config.module.loaders is always returning undefined from webpack.config.js

**Comment by Lelouch-666** [comment]
Any solution?
