### ISSUE TITLE
npm start crush

### ISSUE THREAD

**Issue by tsvetkovpro** [fullstackreact/react-yelp-clone#5]
good day, in this [article](https://www.fullstackreact.com/articles/react-tutorial-cloning-yelp/)  i can't run npm start script . 

i write nmp start in console ang got error: 
```
$ npm start

cloning-yelp@1.0.0 start c:\OpenServer\domains\cloning-yelp NODE_ENV=development hjs-dev-server
"NODE_ENV" ▒▒ ▒▒▒▒ ▒▒▒▒७▒▒▒ ▒▒▒ ▒▒▒譥▒ ▒▒▒▒▒▒▒▒, ▒ᯮ▒▒塞▒▒ ▒ணࠬ▒▒▒ ▒▒▒ ▒▒▒▒▒▒ 䠩▒▒▒.

npm ERR! Windows_NT 10.0.10586 npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start" npm ERR! node v6.2.0 npm ERR! npm v3.8.9 npm ERR! code ELIFECYCLE npm ERR! cloning-yelp@1.0.0 start: NODE_ENV=development hjs-dev-server npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the cloning-yelp@1.0.0 start script 'NODE_ENV=development hjs-dev-server'. npm ERR! Make sure you have the latest version of node.js and npm installed. npm ERR! If you do, this is most likely a problem with the cloning-yelp package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR! NODE_ENV=development hjs-dev-server npm ERR! You can get information on how to open an issue for this project with: npm ERR! npm bugs cloning-yelp npm ERR! Or if that isn't available, you can get their info via: npm ERR! npm owner ls cloning-yelp npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request: npm ERR! c:\OpenServer\domains\cloning-yelp\npm-debug.log
```

what i did wrong? 

p.s. and if i directly write NODE_ENV=development ./node_modules/.bin/hjs-dev-server . it's work fine

**Comment by tsvetkovpro** [comment]
C:\Users\user>npm --version
**3.8.9**

C:\Users\user>node --version
**v6.2.0**


npm-debug.log : 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle clonning-yelp@1.0.0~prestart: clonning-yelp@1.0.0
6 silly lifecycle clonning-yelp@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle clonning-yelp@1.0.0~start: clonning-yelp@1.0.0
8 verbose lifecycle clonning-yelp@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle clonning-yelp@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\OpenServer\domains\cloning-yelp\node_modules\.bin;C:\Program Files\nodejs;C:\Users\user\bin;C:\Program Files (x86)\SmartGit\git\mingw32\bin;C:\Program Files (x86)\SmartGit\git\usr\local\bin;C:\Program Files (x86)\SmartGit\git\usr\bin;C:\Program Files (x86)\SmartGit\git\usr\bin;C:\Program Files (x86)\SmartGit\git\mingw32\bin;C:\Program Files (x86)\SmartGit\git\usr\bin;C:\Users\user\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;node_modules\.bin;C:\OpenServer\domains\node_modules\.bin;C:\OpenServer\node_modules\.bin;C:\Program Files (x86)\SmartGit\git\usr\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Skype\Phone;C:\Users\user\AppData\Roaming\npm;C:\program files (x86)\smartgit\jre\bin;C:\Program Files (x86)\SmartGit\git\usr\bin\vendor_perl;C:\Program Files (x86)\SmartGit\git\usr\bin\core_perl
10 verbose lifecycle clonning-yelp@1.0.0~start: CWD: c:\OpenServer\domains\cloning-yelp
11 silly lifecycle clonning-yelp@1.0.0~start: Args: [ '/d /s /c', 'NODE_ENV=development hjs-dev-server' ]
12 silly lifecycle clonning-yelp@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle clonning-yelp@1.0.0~start: Failed to exec start script
14 verbose stack Error: clonning-yelp@1.0.0 start: `NODE_ENV=development hjs-dev-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid clonning-yelp@1.0.0
16 verbose cwd c:\OpenServer\domains\cloning-yelp
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error clonning-yelp@1.0.0 start: `NODE_ENV=development hjs-dev-server`
22 error Exit status 1
23 error Failed at the clonning-yelp@1.0.0 start script 'NODE_ENV=development hjs-dev-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the clonning-yelp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=development hjs-dev-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs clonning-yelp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls clonning-yelp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by auser** [comment]
What does your `$PATH` look like, @tsvetkovpro?

`echo $PATH`
