### ISSUE TITLE
Erros on trying to copy from

### ISSUE THREAD

**Issue by ivanberry** [fullstackreact/react-yelp-clone#7]
First, thank you guys effort to let us get the skill of react,Thanks!
while , I `yo react-gen`，this is some errors happen like something missed:

>AssertionError: Trying to copy from a source that does not exist: /Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/generators/app/templates/.env
    at EditionInterface.exports._copySingle (/Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at tplCopy (/Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/generators/app/index.js:7:11)
    at /Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/generators/app/index.js:17:5
    at Array.forEach (native)
    at dest (/Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/generators/app/index.js:16:9)
    at module.exports.yeoman.Base.extend.prompting.writing.features.forEach [as writing] (/Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/generators/app/index.js:133:5)
    at Object.<anonymous> (/Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/ivan/.npm-packages/lib/node_modules/generator-react-gen/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25

Is there any thing I did't get? It's look like somethig removed from NPM?

node version:  v4.4.1
npm version:  v2.14.20
yo version: 1.8.4

**Comment by auser** [comment]
This is fixed in the generator-react-gen

**Comment by kitdemonio** [comment]
I solved this problem by creating file .env with [this](https://github.com/fullstackreact/react-gen-generator/commit/fa04b3bce1d7076e2437b6e15ccb0c129b5382e0) content  in C:\Users\...\AppData\Roaming\npm\node_modules\generator-react-gen\generators\app\templates\ , because `npm install -g generator-react-gen` don't create this file automatically
